services:
  onfly-app:
    restart: always
    environment:
      - ENV=local
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    container_name: onflyapp
    depends_on:
      onfly-db:
        condition: service_healthy
  onfly-db:
    image: mysql:8.0.40
    restart: always
    environment:
      - MYSQL_DATABASE=onflydb
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-pass}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-root}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - onflydb:/var/lib/mysql
      - ./migrations/order.sql:/docker-entrypoint-initdb.d/order.sql
    container_name: onflydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
volumes:
  onflydb: